-- MySQL Script generated by MySQL Workbench
-- Sun 23 Jul 2023 05:14:46 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema classroom_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema classroom_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classroom_db` DEFAULT CHARACTER SET utf8 ;
USE `classroom_db` ;

-- -----------------------------------------------------
-- Table `classroom_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classroom_db`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NOT NULL,
  `users_email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classroom_db`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classroom_db`.`classes` (
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `class_name` VARCHAR(255) NOT NULL,
  `classe_title` VARCHAR(255) NOT NULL,
  `class_link` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classroom_db`.`user_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classroom_db`.`user_classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `is_teacher` BOOLEAN NULL,
  PRIMARY KEY (`id`),
  INDEX `student_class_idx` (`class_id` ASC) VISIBLE,
  INDEX `student_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `student_class`
    FOREIGN KEY (`class_id`)
    REFERENCES `classroom_db`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `classroom_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classroom_db`.`assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classroom_db`.`assignments` (
  `assignment_id` INT NOT NULL AUTO_INCREMENT,
  `assignment_title` VARCHAR(255) NULL,
  `assignment_description` TEXT NULL,
  `assignment_teacher` INT NOT NULL,
  `assignment_due_date` DATETIME NOT NULL,
  `assignment_class` INT NOT NULL,
  PRIMARY KEY (`assignment_id`),
  INDEX `user_id_idx` (`assignment_teacher` ASC) VISIBLE,
  INDEX `assignment_class_idx` (`assignment_class` ASC) VISIBLE,
  CONSTRAINT `assignment_class`
    FOREIGN KEY (`assignment_class`)
    REFERENCES `classroom_db`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `assignment_teacher`
    FOREIGN KEY (`assignment_teacher`)
    REFERENCES `classroom_db`.`user_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classroom_db`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classroom_db`.`posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `post_title` VARCHAR(45) NULL,
  `post_description` TEXT NULL,
  `post_class` INT NOT NULL,
  `post_teacher` INT NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `post_class_idx` (`post_class` ASC) VISIBLE,
  INDEX `post_teacher_idx` (`post_teacher` ASC) VISIBLE,
  CONSTRAINT `post_class`
    FOREIGN KEY (`post_class`)
    REFERENCES `classroom_db`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_teacher`
    FOREIGN KEY (`post_teacher`)
    REFERENCES `classroom_db`.`user_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classroom_db`.`user_assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classroom_db`.`user_assignments` (
  `submition_id` INT NOT NULL AUTO_INCREMENT,
  `grade` INT NULL,
  `assignment_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`submition_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `assignment_id_idx` (`assignment_id` ASC) VISIBLE,
  CONSTRAINT `assignment_id`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `classroom_db`.`assignments` (`assignment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `classroom_db`.`user_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
